/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservaRouteImport } from './routes/reserva'
import { Route as PreciosRouteImport } from './routes/precios'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MisComunidadesRouteImport } from './routes/mis-comunidades'
import { Route as MembresiaRouteImport } from './routes/membresia'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as SignupRouteRouteImport } from './routes/signup/route'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as PinRouteRouteImport } from './routes/pin/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as ForgotRouteRouteImport } from './routes/forgot/route'
import { Route as ChangepasswordRouteRouteImport } from './routes/changepassword/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservasIndexRouteImport } from './routes/reservas/index'
import { Route as ComunidadesIndexRouteImport } from './routes/comunidades/index'
import { Route as ReservaServiciosRouteImport } from './routes/reserva/servicios'
import { Route as ReservaLocationProfessionalRouteImport } from './routes/reserva/location-professional'
import { Route as ReservaHorarioRouteImport } from './routes/reserva/horario'
import { Route as ReservaConfirmacionRouteImport } from './routes/reserva/confirmacion'
import { Route as OnboardingMembresiaRouteImport } from './routes/onboarding/membresia'
import { Route as HistorialReservasCommunityIdRouteImport } from './routes/historial-reservas/$communityId'
import { Route as HistorialMembresiasCommunityIdRouteImport } from './routes/historial-membresias/$communityId'
import { Route as ComunidadesCommunityIdRouteRouteImport } from './routes/comunidades/$communityId/route'

const ReservaRoute = ReservaRouteImport.update({
  id: '/reserva',
  path: '/reserva',
  getParentRoute: () => rootRouteImport,
} as any)
const PreciosRoute = PreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MisComunidadesRoute = MisComunidadesRouteImport.update({
  id: '/mis-comunidades',
  path: '/mis-comunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const MembresiaRoute = MembresiaRouteImport.update({
  id: '/membresia',
  path: '/membresia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRouteRoute = SignupRouteRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PinRouteRoute = PinRouteRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRouteRoute = ForgotRouteRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangepasswordRouteRoute = ChangepasswordRouteRouteImport.update({
  id: '/changepassword',
  path: '/changepassword',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasIndexRoute = ReservasIndexRouteImport.update({
  id: '/reservas/',
  path: '/reservas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadesIndexRoute = ComunidadesIndexRouteImport.update({
  id: '/comunidades/',
  path: '/comunidades/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaServiciosRoute = ReservaServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => ReservaRoute,
} as any)
const ReservaLocationProfessionalRoute =
  ReservaLocationProfessionalRouteImport.update({
    id: '/location-professional',
    path: '/location-professional',
    getParentRoute: () => ReservaRoute,
  } as any)
const ReservaHorarioRoute = ReservaHorarioRouteImport.update({
  id: '/horario',
  path: '/horario',
  getParentRoute: () => ReservaRoute,
} as any)
const ReservaConfirmacionRoute = ReservaConfirmacionRouteImport.update({
  id: '/confirmacion',
  path: '/confirmacion',
  getParentRoute: () => ReservaRoute,
} as any)
const OnboardingMembresiaRoute = OnboardingMembresiaRouteImport.update({
  id: '/onboarding/membresia',
  path: '/onboarding/membresia',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialReservasCommunityIdRoute =
  HistorialReservasCommunityIdRouteImport.update({
    id: '/historial-reservas/$communityId',
    path: '/historial-reservas/$communityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const HistorialMembresiasCommunityIdRoute =
  HistorialMembresiasCommunityIdRouteImport.update({
    id: '/historial-membresias/$communityId',
    path: '/historial-membresias/$communityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComunidadesCommunityIdRouteRoute =
  ComunidadesCommunityIdRouteRouteImport.update({
    id: '/comunidades/$communityId',
    path: '/comunidades/$communityId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changepassword': typeof ChangepasswordRouteRoute
  '/forgot': typeof ForgotRouteRoute
  '/home': typeof HomeRouteRoute
  '/login': typeof LoginRouteRoute
  '/pin': typeof PinRouteRoute
  '/profile': typeof ProfileRouteRoute
  '/signup': typeof SignupRouteRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/membresia': typeof MembresiaRoute
  '/mis-comunidades': typeof MisComunidadesRoute
  '/perfil': typeof PerfilRoute
  '/precios': typeof PreciosRoute
  '/reserva': typeof ReservaRouteWithChildren
  '/comunidades/$communityId': typeof ComunidadesCommunityIdRouteRoute
  '/historial-membresias/$communityId': typeof HistorialMembresiasCommunityIdRoute
  '/historial-reservas/$communityId': typeof HistorialReservasCommunityIdRoute
  '/onboarding/membresia': typeof OnboardingMembresiaRoute
  '/reserva/confirmacion': typeof ReservaConfirmacionRoute
  '/reserva/horario': typeof ReservaHorarioRoute
  '/reserva/location-professional': typeof ReservaLocationProfessionalRoute
  '/reserva/servicios': typeof ReservaServiciosRoute
  '/comunidades': typeof ComunidadesIndexRoute
  '/reservas': typeof ReservasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changepassword': typeof ChangepasswordRouteRoute
  '/forgot': typeof ForgotRouteRoute
  '/home': typeof HomeRouteRoute
  '/login': typeof LoginRouteRoute
  '/pin': typeof PinRouteRoute
  '/profile': typeof ProfileRouteRoute
  '/signup': typeof SignupRouteRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/membresia': typeof MembresiaRoute
  '/mis-comunidades': typeof MisComunidadesRoute
  '/perfil': typeof PerfilRoute
  '/precios': typeof PreciosRoute
  '/reserva': typeof ReservaRouteWithChildren
  '/comunidades/$communityId': typeof ComunidadesCommunityIdRouteRoute
  '/historial-membresias/$communityId': typeof HistorialMembresiasCommunityIdRoute
  '/historial-reservas/$communityId': typeof HistorialReservasCommunityIdRoute
  '/onboarding/membresia': typeof OnboardingMembresiaRoute
  '/reserva/confirmacion': typeof ReservaConfirmacionRoute
  '/reserva/horario': typeof ReservaHorarioRoute
  '/reserva/location-professional': typeof ReservaLocationProfessionalRoute
  '/reserva/servicios': typeof ReservaServiciosRoute
  '/comunidades': typeof ComunidadesIndexRoute
  '/reservas': typeof ReservasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changepassword': typeof ChangepasswordRouteRoute
  '/forgot': typeof ForgotRouteRoute
  '/home': typeof HomeRouteRoute
  '/login': typeof LoginRouteRoute
  '/pin': typeof PinRouteRoute
  '/profile': typeof ProfileRouteRoute
  '/signup': typeof SignupRouteRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/membresia': typeof MembresiaRoute
  '/mis-comunidades': typeof MisComunidadesRoute
  '/perfil': typeof PerfilRoute
  '/precios': typeof PreciosRoute
  '/reserva': typeof ReservaRouteWithChildren
  '/comunidades/$communityId': typeof ComunidadesCommunityIdRouteRoute
  '/historial-membresias/$communityId': typeof HistorialMembresiasCommunityIdRoute
  '/historial-reservas/$communityId': typeof HistorialReservasCommunityIdRoute
  '/onboarding/membresia': typeof OnboardingMembresiaRoute
  '/reserva/confirmacion': typeof ReservaConfirmacionRoute
  '/reserva/horario': typeof ReservaHorarioRoute
  '/reserva/location-professional': typeof ReservaLocationProfessionalRoute
  '/reserva/servicios': typeof ReservaServiciosRoute
  '/comunidades/': typeof ComunidadesIndexRoute
  '/reservas/': typeof ReservasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changepassword'
    | '/forgot'
    | '/home'
    | '/login'
    | '/pin'
    | '/profile'
    | '/signup'
    | '/como-funciona'
    | '/contacto'
    | '/membresia'
    | '/mis-comunidades'
    | '/perfil'
    | '/precios'
    | '/reserva'
    | '/comunidades/$communityId'
    | '/historial-membresias/$communityId'
    | '/historial-reservas/$communityId'
    | '/onboarding/membresia'
    | '/reserva/confirmacion'
    | '/reserva/horario'
    | '/reserva/location-professional'
    | '/reserva/servicios'
    | '/comunidades'
    | '/reservas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changepassword'
    | '/forgot'
    | '/home'
    | '/login'
    | '/pin'
    | '/profile'
    | '/signup'
    | '/como-funciona'
    | '/contacto'
    | '/membresia'
    | '/mis-comunidades'
    | '/perfil'
    | '/precios'
    | '/reserva'
    | '/comunidades/$communityId'
    | '/historial-membresias/$communityId'
    | '/historial-reservas/$communityId'
    | '/onboarding/membresia'
    | '/reserva/confirmacion'
    | '/reserva/horario'
    | '/reserva/location-professional'
    | '/reserva/servicios'
    | '/comunidades'
    | '/reservas'
  id:
    | '__root__'
    | '/'
    | '/changepassword'
    | '/forgot'
    | '/home'
    | '/login'
    | '/pin'
    | '/profile'
    | '/signup'
    | '/como-funciona'
    | '/contacto'
    | '/membresia'
    | '/mis-comunidades'
    | '/perfil'
    | '/precios'
    | '/reserva'
    | '/comunidades/$communityId'
    | '/historial-membresias/$communityId'
    | '/historial-reservas/$communityId'
    | '/onboarding/membresia'
    | '/reserva/confirmacion'
    | '/reserva/horario'
    | '/reserva/location-professional'
    | '/reserva/servicios'
    | '/comunidades/'
    | '/reservas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangepasswordRouteRoute: typeof ChangepasswordRouteRoute
  ForgotRouteRoute: typeof ForgotRouteRoute
  HomeRouteRoute: typeof HomeRouteRoute
  LoginRouteRoute: typeof LoginRouteRoute
  PinRouteRoute: typeof PinRouteRoute
  ProfileRouteRoute: typeof ProfileRouteRoute
  SignupRouteRoute: typeof SignupRouteRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContactoRoute: typeof ContactoRoute
  MembresiaRoute: typeof MembresiaRoute
  MisComunidadesRoute: typeof MisComunidadesRoute
  PerfilRoute: typeof PerfilRoute
  PreciosRoute: typeof PreciosRoute
  ReservaRoute: typeof ReservaRouteWithChildren
  ComunidadesCommunityIdRouteRoute: typeof ComunidadesCommunityIdRouteRoute
  HistorialMembresiasCommunityIdRoute: typeof HistorialMembresiasCommunityIdRoute
  HistorialReservasCommunityIdRoute: typeof HistorialReservasCommunityIdRoute
  OnboardingMembresiaRoute: typeof OnboardingMembresiaRoute
  ComunidadesIndexRoute: typeof ComunidadesIndexRoute
  ReservasIndexRoute: typeof ReservasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reserva': {
      id: '/reserva'
      path: '/reserva'
      fullPath: '/reserva'
      preLoaderRoute: typeof ReservaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precios': {
      id: '/precios'
      path: '/precios'
      fullPath: '/precios'
      preLoaderRoute: typeof PreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-comunidades': {
      id: '/mis-comunidades'
      path: '/mis-comunidades'
      fullPath: '/mis-comunidades'
      preLoaderRoute: typeof MisComunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membresia': {
      id: '/membresia'
      path: '/membresia'
      fullPath: '/membresia'
      preLoaderRoute: typeof MembresiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin': {
      id: '/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof PinRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changepassword': {
      id: '/changepassword'
      path: '/changepassword'
      fullPath: '/changepassword'
      preLoaderRoute: typeof ChangepasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas/': {
      id: '/reservas/'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidades/': {
      id: '/comunidades/'
      path: '/comunidades'
      fullPath: '/comunidades'
      preLoaderRoute: typeof ComunidadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva/servicios': {
      id: '/reserva/servicios'
      path: '/servicios'
      fullPath: '/reserva/servicios'
      preLoaderRoute: typeof ReservaServiciosRouteImport
      parentRoute: typeof ReservaRoute
    }
    '/reserva/location-professional': {
      id: '/reserva/location-professional'
      path: '/location-professional'
      fullPath: '/reserva/location-professional'
      preLoaderRoute: typeof ReservaLocationProfessionalRouteImport
      parentRoute: typeof ReservaRoute
    }
    '/reserva/horario': {
      id: '/reserva/horario'
      path: '/horario'
      fullPath: '/reserva/horario'
      preLoaderRoute: typeof ReservaHorarioRouteImport
      parentRoute: typeof ReservaRoute
    }
    '/reserva/confirmacion': {
      id: '/reserva/confirmacion'
      path: '/confirmacion'
      fullPath: '/reserva/confirmacion'
      preLoaderRoute: typeof ReservaConfirmacionRouteImport
      parentRoute: typeof ReservaRoute
    }
    '/onboarding/membresia': {
      id: '/onboarding/membresia'
      path: '/onboarding/membresia'
      fullPath: '/onboarding/membresia'
      preLoaderRoute: typeof OnboardingMembresiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial-reservas/$communityId': {
      id: '/historial-reservas/$communityId'
      path: '/historial-reservas/$communityId'
      fullPath: '/historial-reservas/$communityId'
      preLoaderRoute: typeof HistorialReservasCommunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial-membresias/$communityId': {
      id: '/historial-membresias/$communityId'
      path: '/historial-membresias/$communityId'
      fullPath: '/historial-membresias/$communityId'
      preLoaderRoute: typeof HistorialMembresiasCommunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidades/$communityId': {
      id: '/comunidades/$communityId'
      path: '/comunidades/$communityId'
      fullPath: '/comunidades/$communityId'
      preLoaderRoute: typeof ComunidadesCommunityIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReservaRouteChildren {
  ReservaConfirmacionRoute: typeof ReservaConfirmacionRoute
  ReservaHorarioRoute: typeof ReservaHorarioRoute
  ReservaLocationProfessionalRoute: typeof ReservaLocationProfessionalRoute
  ReservaServiciosRoute: typeof ReservaServiciosRoute
}

const ReservaRouteChildren: ReservaRouteChildren = {
  ReservaConfirmacionRoute: ReservaConfirmacionRoute,
  ReservaHorarioRoute: ReservaHorarioRoute,
  ReservaLocationProfessionalRoute: ReservaLocationProfessionalRoute,
  ReservaServiciosRoute: ReservaServiciosRoute,
}

const ReservaRouteWithChildren =
  ReservaRoute._addFileChildren(ReservaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangepasswordRouteRoute: ChangepasswordRouteRoute,
  ForgotRouteRoute: ForgotRouteRoute,
  HomeRouteRoute: HomeRouteRoute,
  LoginRouteRoute: LoginRouteRoute,
  PinRouteRoute: PinRouteRoute,
  ProfileRouteRoute: ProfileRouteRoute,
  SignupRouteRoute: SignupRouteRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContactoRoute: ContactoRoute,
  MembresiaRoute: MembresiaRoute,
  MisComunidadesRoute: MisComunidadesRoute,
  PerfilRoute: PerfilRoute,
  PreciosRoute: PreciosRoute,
  ReservaRoute: ReservaRouteWithChildren,
  ComunidadesCommunityIdRouteRoute: ComunidadesCommunityIdRouteRoute,
  HistorialMembresiasCommunityIdRoute: HistorialMembresiasCommunityIdRoute,
  HistorialReservasCommunityIdRoute: HistorialReservasCommunityIdRoute,
  OnboardingMembresiaRoute: OnboardingMembresiaRoute,
  ComunidadesIndexRoute: ComunidadesIndexRoute,
  ReservasIndexRoute: ReservasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
