/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as NotFoundPageImport } from './routes/NotFoundPage'
import { Route as SesionesRouteImport } from './routes/sesiones/route'
import { Route as ServiciosRouteImport } from './routes/servicios/route'
import { Route as RolesPermisosRouteImport } from './routes/roles-permisos/route'
import { Route as ReportesRouteImport } from './routes/reportes/route'
import { Route as PlanesMembresiaRouteImport } from './routes/planes-membresia/route'
import { Route as MembresiasRouteImport } from './routes/membresias/route'
import { Route as LogErroresRouteImport } from './routes/log-errores/route'
import { Route as LocalesRouteImport } from './routes/locales/route'
import { Route as AuditoriaRouteImport } from './routes/auditoria/route'
import { Route as IndexImport } from './routes/index'
import { Route as ProfesionalesIndexImport } from './routes/profesionales/index'
import { Route as ComunidadesIndexImport } from './routes/comunidades/index'
import { Route as ProfesionalesVerImport } from './routes/profesionales/ver'
import { Route as ProfesionalesNuevoImport } from './routes/profesionales/nuevo'
import { Route as ComunidadesNuevoImport } from './routes/comunidades/nuevo'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const NotFoundPageRoute = NotFoundPageImport.update({
  id: '/NotFoundPage',
  path: '/NotFoundPage',
  getParentRoute: () => rootRoute,
} as any)

const SesionesRouteRoute = SesionesRouteImport.update({
  id: '/sesiones',
  path: '/sesiones',
  getParentRoute: () => rootRoute,
} as any)

const ServiciosRouteRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRoute,
} as any)

const RolesPermisosRouteRoute = RolesPermisosRouteImport.update({
  id: '/roles-permisos',
  path: '/roles-permisos',
  getParentRoute: () => rootRoute,
} as any)

const ReportesRouteRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRoute,
} as any)

const PlanesMembresiaRouteRoute = PlanesMembresiaRouteImport.update({
  id: '/planes-membresia',
  path: '/planes-membresia',
  getParentRoute: () => rootRoute,
} as any)

const MembresiasRouteRoute = MembresiasRouteImport.update({
  id: '/membresias',
  path: '/membresias',
  getParentRoute: () => rootRoute,
} as any)

const LogErroresRouteRoute = LogErroresRouteImport.update({
  id: '/log-errores',
  path: '/log-errores',
  getParentRoute: () => rootRoute,
} as any)

const LocalesRouteRoute = LocalesRouteImport.update({
  id: '/locales',
  path: '/locales',
  getParentRoute: () => rootRoute,
} as any)

const AuditoriaRouteRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfesionalesIndexRoute = ProfesionalesIndexImport.update({
  id: '/profesionales/',
  path: '/profesionales/',
  getParentRoute: () => rootRoute,
} as any)

const ComunidadesIndexRoute = ComunidadesIndexImport.update({
  id: '/comunidades/',
  path: '/comunidades/',
  getParentRoute: () => rootRoute,
} as any)

const ProfesionalesVerRoute = ProfesionalesVerImport.update({
  id: '/profesionales/ver',
  path: '/profesionales/ver',
  getParentRoute: () => rootRoute,
} as any)

const ProfesionalesNuevoRoute = ProfesionalesNuevoImport.update({
  id: '/profesionales/nuevo',
  path: '/profesionales/nuevo',
  getParentRoute: () => rootRoute,
} as any)

const ComunidadesNuevoRoute = ComunidadesNuevoImport.update({
  id: '/comunidades/nuevo',
  path: '/comunidades/nuevo',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRoute
    }
    '/locales': {
      id: '/locales'
      path: '/locales'
      fullPath: '/locales'
      preLoaderRoute: typeof LocalesRouteImport
      parentRoute: typeof rootRoute
    }
    '/log-errores': {
      id: '/log-errores'
      path: '/log-errores'
      fullPath: '/log-errores'
      preLoaderRoute: typeof LogErroresRouteImport
      parentRoute: typeof rootRoute
    }
    '/membresias': {
      id: '/membresias'
      path: '/membresias'
      fullPath: '/membresias'
      preLoaderRoute: typeof MembresiasRouteImport
      parentRoute: typeof rootRoute
    }
    '/planes-membresia': {
      id: '/planes-membresia'
      path: '/planes-membresia'
      fullPath: '/planes-membresia'
      preLoaderRoute: typeof PlanesMembresiaRouteImport
      parentRoute: typeof rootRoute
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRoute
    }
    '/roles-permisos': {
      id: '/roles-permisos'
      path: '/roles-permisos'
      fullPath: '/roles-permisos'
      preLoaderRoute: typeof RolesPermisosRouteImport
      parentRoute: typeof rootRoute
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRoute
    }
    '/sesiones': {
      id: '/sesiones'
      path: '/sesiones'
      fullPath: '/sesiones'
      preLoaderRoute: typeof SesionesRouteImport
      parentRoute: typeof rootRoute
    }
    '/NotFoundPage': {
      id: '/NotFoundPage'
      path: '/NotFoundPage'
      fullPath: '/NotFoundPage'
      preLoaderRoute: typeof NotFoundPageImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/comunidades/nuevo': {
      id: '/comunidades/nuevo'
      path: '/comunidades/nuevo'
      fullPath: '/comunidades/nuevo'
      preLoaderRoute: typeof ComunidadesNuevoImport
      parentRoute: typeof rootRoute
    }
    '/profesionales/nuevo': {
      id: '/profesionales/nuevo'
      path: '/profesionales/nuevo'
      fullPath: '/profesionales/nuevo'
      preLoaderRoute: typeof ProfesionalesNuevoImport
      parentRoute: typeof rootRoute
    }
    '/profesionales/ver': {
      id: '/profesionales/ver'
      path: '/profesionales/ver'
      fullPath: '/profesionales/ver'
      preLoaderRoute: typeof ProfesionalesVerImport
      parentRoute: typeof rootRoute
    }
    '/comunidades/': {
      id: '/comunidades/'
      path: '/comunidades'
      fullPath: '/comunidades'
      preLoaderRoute: typeof ComunidadesIndexImport
      parentRoute: typeof rootRoute
    }
    '/profesionales/': {
      id: '/profesionales/'
      path: '/profesionales'
      fullPath: '/profesionales'
      preLoaderRoute: typeof ProfesionalesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRouteRoute
  '/locales': typeof LocalesRouteRoute
  '/log-errores': typeof LogErroresRouteRoute
  '/membresias': typeof MembresiasRouteRoute
  '/planes-membresia': typeof PlanesMembresiaRouteRoute
  '/reportes': typeof ReportesRouteRoute
  '/roles-permisos': typeof RolesPermisosRouteRoute
  '/servicios': typeof ServiciosRouteRoute
  '/sesiones': typeof SesionesRouteRoute
  '/NotFoundPage': typeof NotFoundPageRoute
  '/login': typeof LoginRoute
  '/comunidades/nuevo': typeof ComunidadesNuevoRoute
  '/profesionales/nuevo': typeof ProfesionalesNuevoRoute
  '/profesionales/ver': typeof ProfesionalesVerRoute
  '/comunidades': typeof ComunidadesIndexRoute
  '/profesionales': typeof ProfesionalesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRouteRoute
  '/locales': typeof LocalesRouteRoute
  '/log-errores': typeof LogErroresRouteRoute
  '/membresias': typeof MembresiasRouteRoute
  '/planes-membresia': typeof PlanesMembresiaRouteRoute
  '/reportes': typeof ReportesRouteRoute
  '/roles-permisos': typeof RolesPermisosRouteRoute
  '/servicios': typeof ServiciosRouteRoute
  '/sesiones': typeof SesionesRouteRoute
  '/NotFoundPage': typeof NotFoundPageRoute
  '/login': typeof LoginRoute
  '/comunidades/nuevo': typeof ComunidadesNuevoRoute
  '/profesionales/nuevo': typeof ProfesionalesNuevoRoute
  '/profesionales/ver': typeof ProfesionalesVerRoute
  '/comunidades': typeof ComunidadesIndexRoute
  '/profesionales': typeof ProfesionalesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRouteRoute
  '/locales': typeof LocalesRouteRoute
  '/log-errores': typeof LogErroresRouteRoute
  '/membresias': typeof MembresiasRouteRoute
  '/planes-membresia': typeof PlanesMembresiaRouteRoute
  '/reportes': typeof ReportesRouteRoute
  '/roles-permisos': typeof RolesPermisosRouteRoute
  '/servicios': typeof ServiciosRouteRoute
  '/sesiones': typeof SesionesRouteRoute
  '/NotFoundPage': typeof NotFoundPageRoute
  '/login': typeof LoginRoute
  '/comunidades/nuevo': typeof ComunidadesNuevoRoute
  '/profesionales/nuevo': typeof ProfesionalesNuevoRoute
  '/profesionales/ver': typeof ProfesionalesVerRoute
  '/comunidades/': typeof ComunidadesIndexRoute
  '/profesionales/': typeof ProfesionalesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/locales'
    | '/log-errores'
    | '/membresias'
    | '/planes-membresia'
    | '/reportes'
    | '/roles-permisos'
    | '/servicios'
    | '/sesiones'
    | '/NotFoundPage'
    | '/login'
    | '/comunidades/nuevo'
    | '/profesionales/nuevo'
    | '/profesionales/ver'
    | '/comunidades'
    | '/profesionales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/locales'
    | '/log-errores'
    | '/membresias'
    | '/planes-membresia'
    | '/reportes'
    | '/roles-permisos'
    | '/servicios'
    | '/sesiones'
    | '/NotFoundPage'
    | '/login'
    | '/comunidades/nuevo'
    | '/profesionales/nuevo'
    | '/profesionales/ver'
    | '/comunidades'
    | '/profesionales'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/locales'
    | '/log-errores'
    | '/membresias'
    | '/planes-membresia'
    | '/reportes'
    | '/roles-permisos'
    | '/servicios'
    | '/sesiones'
    | '/NotFoundPage'
    | '/login'
    | '/comunidades/nuevo'
    | '/profesionales/nuevo'
    | '/profesionales/ver'
    | '/comunidades/'
    | '/profesionales/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRouteRoute: typeof AuditoriaRouteRoute
  LocalesRouteRoute: typeof LocalesRouteRoute
  LogErroresRouteRoute: typeof LogErroresRouteRoute
  MembresiasRouteRoute: typeof MembresiasRouteRoute
  PlanesMembresiaRouteRoute: typeof PlanesMembresiaRouteRoute
  ReportesRouteRoute: typeof ReportesRouteRoute
  RolesPermisosRouteRoute: typeof RolesPermisosRouteRoute
  ServiciosRouteRoute: typeof ServiciosRouteRoute
  SesionesRouteRoute: typeof SesionesRouteRoute
  NotFoundPageRoute: typeof NotFoundPageRoute
  LoginRoute: typeof LoginRoute
  ComunidadesNuevoRoute: typeof ComunidadesNuevoRoute
  ProfesionalesNuevoRoute: typeof ProfesionalesNuevoRoute
  ProfesionalesVerRoute: typeof ProfesionalesVerRoute
  ComunidadesIndexRoute: typeof ComunidadesIndexRoute
  ProfesionalesIndexRoute: typeof ProfesionalesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRouteRoute: AuditoriaRouteRoute,
  LocalesRouteRoute: LocalesRouteRoute,
  LogErroresRouteRoute: LogErroresRouteRoute,
  MembresiasRouteRoute: MembresiasRouteRoute,
  PlanesMembresiaRouteRoute: PlanesMembresiaRouteRoute,
  ReportesRouteRoute: ReportesRouteRoute,
  RolesPermisosRouteRoute: RolesPermisosRouteRoute,
  ServiciosRouteRoute: ServiciosRouteRoute,
  SesionesRouteRoute: SesionesRouteRoute,
  NotFoundPageRoute: NotFoundPageRoute,
  LoginRoute: LoginRoute,
  ComunidadesNuevoRoute: ComunidadesNuevoRoute,
  ProfesionalesNuevoRoute: ProfesionalesNuevoRoute,
  ProfesionalesVerRoute: ProfesionalesVerRoute,
  ComunidadesIndexRoute: ComunidadesIndexRoute,
  ProfesionalesIndexRoute: ProfesionalesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auditoria",
        "/locales",
        "/log-errores",
        "/membresias",
        "/planes-membresia",
        "/reportes",
        "/roles-permisos",
        "/servicios",
        "/sesiones",
        "/NotFoundPage",
        "/login",
        "/comunidades/nuevo",
        "/profesionales/nuevo",
        "/profesionales/ver",
        "/comunidades/",
        "/profesionales/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auditoria": {
      "filePath": "auditoria/route.tsx"
    },
    "/locales": {
      "filePath": "locales/route.tsx"
    },
    "/log-errores": {
      "filePath": "log-errores/route.tsx"
    },
    "/membresias": {
      "filePath": "membresias/route.tsx"
    },
    "/planes-membresia": {
      "filePath": "planes-membresia/route.tsx"
    },
    "/reportes": {
      "filePath": "reportes/route.tsx"
    },
    "/roles-permisos": {
      "filePath": "roles-permisos/route.tsx"
    },
    "/servicios": {
      "filePath": "servicios/route.tsx"
    },
    "/sesiones": {
      "filePath": "sesiones/route.tsx"
    },
    "/NotFoundPage": {
      "filePath": "NotFoundPage.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/comunidades/nuevo": {
      "filePath": "comunidades/nuevo.tsx"
    },
    "/profesionales/nuevo": {
      "filePath": "profesionales/nuevo.tsx"
    },
    "/profesionales/ver": {
      "filePath": "profesionales/ver.tsx"
    },
    "/comunidades/": {
      "filePath": "comunidades/index.tsx"
    },
    "/profesionales/": {
      "filePath": "profesionales/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
